apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-service
  ports:
    - protocol: TCP
      port: 30081
      targetPort: 80
  type: NodePort # Mude para LoadBalancer se precisar de acesso externo
