# Valores para o Helm chart do MySQL no ambiente de prod.
# Para produção, a persistência é crucial.
# Use o `local-path` provisioner do K3s ou um storage class de um provedor de nuvem.
# Exemplo com local-path:
# primary:
#   persistence:
#     enabled: true
#     storageClass: "local-path"
#     accessModes:
#       - ReadWriteOnce
#     size: 10Gi
#     mountPath: /var/lib/mysql

# auth:
#   rootPassword: "NAO-COLOQUE-SENHAS-AQUI-EM-PROD"
#   database: "db_prod"
#   username: "user_prod"
#   password: "NAO-COLOQUE-SENHAS-AQUI-EM-PROD"

# Para produção, use um mecanismo de secrets como SOPS ou External Secrets.
# Exemplo com SOPS: O `values.yaml` seria criptografado.
# Exemplo com External Secrets: Você criaria um `ExternalSecret`
# que buscaria os valores de um cofre (ex: Azure Key Vault) e criaria
# o Secret do Kubernetes para o MySQL usar.
