apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-path-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-path-provisioner
  template:
    metadata:
      labels:
        app: data-path-provisioner
    spec:
      serviceAccountName: data-path-provisioner-service-account
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
          operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      containers:
        - name: data-path-provisioner
          image: rancher/local-path-provisioner:v0.0.24
          command:
            - local-path-provisioner
            - start
            - --config
            - /etc/config/config.json
            - --provisioner-name
            - cluster.local/data-path
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: data-path-config
