# Valores para o Helm chart do MySQL no ambiente de dev.
# Forçando a tag da imagem para uma versão válida, pois a padrão do chart está obsoleta.
image:
  repository: docker.io/bitnami/mysql
  tag: 8.0.36

# Você pode sobrescrever os valores do chart default aqui.
# Exemplo:
# auth:
#   rootPassword: "seu-password-de-root"
#   database: "sua-db"
#   username: "seu-usuario"
#   password: "sua-senha-de-usuario"
